-- 코드를 작성해주세요
SELECT YEAR(ED.DIFFERENTIATION_DATE) AS YEAR, (SUB.MAX_DEV - ED.SIZE_OF_COLONY) AS YEAR_DEV, ED.ID
FROM ECOLI_DATA ED
JOIN (
    SELECT YEAR(DIFFERENTIATION_DATE) AS Y, MAX(SIZE_OF_COLONY) AS MAX_DEV
    FROM ECOLI_DATA
    GROUP BY Y
) SUB
ON SUBSTRING(ED.DIFFERENTIATION_DATE, 1, 4) = SUB.Y
ORDER BY YEAR ASC, YEAR_DEV ASC;

