-- 코드를 작성해주세요
SELECT FI.ID, FNI.FISH_NAME, FI.LENGTH
FROM FISH_INFO AS FI 
JOIN (
#     서브쿼리로 max length 거르기
    SELECT FISH_TYPE, MAX(LENGTH) AS MAX_LENGTH
    FROM FISH_INFO
    GROUP BY FISH_TYPE
) SUB
ON FI.FISH_TYPE = SUB.FISH_TYPE
AND FI.LENGTH = SUB.MAX_LENGTH

JOIN FISH_NAME_INFO AS FNI ON FI.FISH_TYPE = FNI.FISH_TYPE

ORDER BY FI.ID;